/**
 * Production static server for cPanel CloudLinux Node.js Selector.
 *
 * Serves the static build output (`out/`) generated by `npm run build`
 * (Next.js `output: "export"`). Dependency-free: only Node.js built-ins.
 * The same static export keeps Vercel / Netlify deployments unchanged.
 *
 * CloudLinux Node.js Selector sets the PORT environment variable
 * automatically; no other configuration is required.
 */
const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");

const ROOT = path.join(__dirname, "out");
const PORT = process.env.PORT || 3000;
const HOST = process.env.HOST || "0.0.0.0";

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".eot": "application/vnd.ms-fontobject",
  ".pdf": "application/pdf",
  ".mp4": "video/mp4",
  ".mp3": "audio/mpeg",
};

const SECURITY_HEADERS = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "X-XSS-Protection": "1; mode=block",
  "Referrer-Policy": "strict-origin-when-cross-origin",
};

/** Hashed Next.js assets and images never change — cache them forever. */
const CACHE_FOREVER_PATTERN = /^\/_next\/static\/.*/;

function resolveFile(pathname) {
  let decoded;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    return null;
  }
  if (decoded.includes("\0") || decoded.includes("..")) return null;

  const rel = decoded === "/" ? "index.html" : decoded.replace(/^\/+/, "");
  const file = path.join(ROOT, rel);

  if (fs.existsSync(file) && fs.statSync(file).isFile()) return file;

  if (path.extname(file) === "") {
    const html = `${file}.html`;
    if (fs.existsSync(html)) return html;
    const index = path.join(file, "index.html");
    if (fs.existsSync(index)) return index;
  }
  return null;
}

function sendNotFound(res, statusCode) {
  const notFound = path.join(ROOT, "404.html");
  fs.readFile(notFound, (err, buf) => {
    res.writeHead(statusCode, {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-cache",
      ...SECURITY_HEADERS,
    });
    res.end(err ? "404 Not Found" : buf);
  });
}

function serveFile(req, res, pathname) {
  const file = resolveFile(pathname);
  if (!file) {
    sendNotFound(res, 404);
    return;
  }

  fs.readFile(file, (err, buf) => {
    if (err) {
      sendNotFound(res, 404);
      return;
    }

    const mime = MIME_TYPES[path.extname(file)] || "application/octet-stream";
    const isCompressible = /^text\/|javascript|json|xml|svg|manifest/.test(mime);
    const cacheForever = CACHE_FOREVER_PATTERN.test(pathname);
    const headers = {
      "Content-Type": mime,
      "Cache-Control": cacheForever
        ? "public, max-age=31536000, immutable"
        : "no-cache",
      ...SECURITY_HEADERS,
    };

    if (req.method === "HEAD") {
      headers["Content-Length"] = buf.length;
      res.writeHead(200, headers);
      res.end();
      return;
    }

    if (isCompressible && buf.length > 1024) {
      const acceptEncoding = req.headers["accept-encoding"] || "";
      const sendCompressed = (encoding, data) => {
        headers["Content-Encoding"] = encoding;
        headers["Vary"] = "Accept-Encoding";
        headers["Content-Length"] = data.length;
        res.writeHead(200, headers);
        res.end(data);
      };
      if (acceptEncoding.includes("br")) {
        return sendCompressed("br", zlib.brotliCompressSync(buf));
      }
      if (acceptEncoding.includes("gzip")) {
        return sendCompressed("gzip", zlib.gzipSync(buf));
      }
    }

    headers["Content-Length"] = buf.length;
    res.writeHead(200, headers);
    res.end(buf);
  });
}

const server = http.createServer((req, res) => {
  const pathname = new URL(req.url, `http://${req.headers.host || "localhost"}`)
    .pathname;
  serveFile(req, res, pathname);
});

server.listen(PORT, HOST, () => {
  console.log(`Fahim Pharmacy server running at http://${HOST}:${PORT}`);
  console.log(`Serving static build from: ${ROOT}`);
});